<a href="https://colab.research.google.com/github/hinojosaM/Homework_1/blob/main/Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(pd.__version__)

2.2.3


In [ ]:
# Download the dataset using wget
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

# Load the dataset into a DataFrame
df = pd.read_csv('car_fuel_efficiency_2026.csv')

# Inspect the first few rows
df.head()



--2026-09-29 03:20:55--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.04s   

2026-09-29 03:20:55 (14.5 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]



,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [ ]:
# Q2: Count the total number of records
num_records = len(df)
print(f"Total number of records: {num_records}")


Total number of records: 10000


In [ ]:
# Identify the fuel type column
fuel_column = 'fuel_type' if 'fuel_type' in df.columns else 'fuel'

# Q3: Count distinct fuel types
num_fuel_types = df[fuel_column].nunique()
print(f"Number of fuel types: {num_fuel_types}")
print("Unique fuel types:", df[fuel_column].unique())

Number of fuel types: 3
Unique fuel types: ['Gasoline' 'Diesel' 'Hybrid']


In [ ]:
# Check count of missing values per column
missing_per_column = df.isnull().sum()
print("Missing values per column:\n", missing_per_column)

# Q4: Count how many columns contain at least one missing value
cols_with_missing = (missing_per_column > 0).sum()
print(f"\nNumber of columns with missing values: {cols_with_missing}")

Missing values per column:
 model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Number of columns with missing values: 2


In [ ]:
# Find the exact efficiency column name
efficiency_col = [col for col in df.columns if 'efficiency' in col or 'mpg' in col][0]

# Q5: Filter cars from Asia and find the maximum efficiency
max_asia_efficiency = df[df['origin'] == 'Asia'][efficiency_col].max()

print(f"Using column: {efficiency_col}")
print(f"Maximum fuel efficiency for cars from Asia: {max_asia_efficiency}")

Using column: fuel_efficiency_mpg
Maximum fuel efficiency for cars from Asia: 41.2


In [ ]:
# 1. Calculate the initial median
initial_median = df['horsepower'].median()
print(f"Initial median of horsepower: {initial_median}")

# 2. Calculate the most frequent value (mode)
horsepower_mode = df['horsepower'].mode()[0]
print(f"Most frequent value (mode): {horsepower_mode}")

# 3. Fill missing values with the mode on a copy of the dataframe
df_imputed = df.copy()
df_imputed['horsepower'] = df_imputed['horsepower'].fillna(horsepower_mode)

# 4. Calculate the median after imputation
updated_median = df_imputed['horsepower'].median()
print(f"Updated median of horsepower: {updated_median}")

# 5. Check if the median changed
if updated_median > initial_median:
    print("Answer: Yes, it increased")
elif updated_median < initial_median:
    print("Answer: Yes, it decreased")
else:
    print("Answer: No")


Initial median of horsepower: 254.0
Most frequent value (mode): 252.0
Updated median of horsepower: 252.0
Answer: Yes, it decreased


In [ ]:
# 1 & 2. Filter cars from Asia and select 'vehicle_weight' and 'model_year'
asia_cars = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

# 3. Select the first 7 values
asia_subset = asia_cars.iloc[:7]

# 4. Convert to NumPy array X
X = asia_subset.to_numpy()
print("Matrix X shape:", X.shape)
print("Matrix X:\n", X)

# 5. Compute matrix-matrix multiplication: X^T * X
XTX = X.T @ X
print("\nXTX:\n", XTX)

# 6. Invert XTX
XTX_inv = np.linalg.inv(XTX)
print("\nInverse of XTX:\n", XTX_inv)

# 7. Create target array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 8. Compute weight vector w = (X^T * X)^(-1) * X^T * y
w = XTX_inv @ X.T @ y
print("\nWeight vector w:", w)

# 9. Calculate the sum of all elements in w
sum_of_weights = np.sum(w)
print(f"\nSum of all elements in w: {sum_of_weights:.4f}")

Matrix X shape: (7, 2)
Matrix X:
 [[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

XTX:
 [[131950500  60750580]
 [ 60750580  28041424]]

Inverse of XTX:
 [[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

Weight vector w: [0.13644777 0.2327492 ]

Sum of all elements in w: 0.3692
